/**
 * Copyright 2016, GeoSolutions Sas.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
  * Please, keep them sorted alphabetically
 */
module.exports = {
    plugins: {
        // product plugins
        AboutPlugin: require('./plugins/About'),
        AttributionPlugin: require('./plugins/Attribution'),
        ExamplesPlugin: require('./plugins/Examples'),
        FooterPlugin: require('./plugins/Footer'),
        ForkPlugin: require('./plugins/Fork'),
        HeaderPlugin: require('./plugins/Header'),
        HomeDescriptionPlugin: require('./plugins/HomeDescription'),
        MadeWithLovePlugin: require('./plugins/MadeWithLove'),
        MailingListsPlugin: require('./plugins/MailingLists'),
        MapTypePlugin: require('./plugins/MapType'),
        NavMenu: require('./plugins/NavMenu'),
        // framework plugins
        AddGroupPlugin: require('../../../framework/plugins/AddGroup').default,
        AnnotationsPlugin: require('../../../framework/plugins/Annotations'),
        AutoMapUpdatePlugin: require('../../../framework/plugins/AutoMapUpdate'),
        BackgroundSelectorPlugin: require('../../../framework/plugins/BackgroundSelector'),
        BackgroundSwitcherPlugin: require('../../../framework/plugins/BackgroundSwitcher'),
        BurgerMenuPlugin: require('../../../framework/plugins/BurgerMenu'),
        CRSSelectorPlugin: require('../../../framework/plugins/CRSSelector'),
        ContentTabs: require('../../../framework/plugins/ContentTabs'),
        ContextPlugin: require('../../../framework/plugins/Context').default,
        ContextCreatorPlugin: require('../../../framework/plugins/ContextCreator').default,
        ContextManagerPlugin: require('../../../framework/plugins/contextmanager/ContextManager').default,
        CookiePlugin: require('../../../framework/plugins/Cookie'),
        CreateNewMapPlugin: require('../../../framework/plugins/CreateNewMap').default,
        Dashboard: require('../../../framework/plugins/Dashboard'),
        DashboardEditor: require('../../../framework/plugins/DashboardEditor'),
        DashboardsPlugin: require('../../../framework/plugins/Dashboards'),
        DetailsPlugin: require('../../../framework/plugins/Details'),
        DrawerMenuPlugin: require('../../../framework/plugins/DrawerMenu'),
        ExpanderPlugin: require('../../../framework/plugins/Expander'),
        FeatureEditorPlugin: require('../../../framework/plugins/FeatureEditor').default,
        FeaturedMaps: require('../../../framework/plugins/FeaturedMaps'),
        FeedbackMaskPlugin: require('../../../framework/plugins/FeedbackMask'),
        FilterLayerPlugin: require('../../../framework/plugins/FilterLayer').default,
        FloatingLegendPlugin: require('../../../framework/plugins/FloatingLegend'),
        FullScreenPlugin: require('../../../framework/plugins/FullScreen'),
        GeoStoryPlugin: require('../../../framework/plugins/GeoStory').default,
        GeoStoriesPlugin: require('../../../framework/plugins/GeoStories'),
        GeoStoryEditorPlugin: require('../../../framework/plugins/GeoStoryEditor').default,
        GeoStorySavePlugin: require('../../../framework/plugins/GeoStorySave').GeoStorySave,
        GeoStorySaveAsPlugin: require('../../../framework/plugins/GeoStorySave').GeoStorySaveAs,
        DashboardSavePlugin: require('../../../framework/plugins/DashboardSave').DashboardSave,
        DashboardSaveAsPlugin: require('../../../framework/plugins/DashboardSave').DashboardSaveAs,
        GeoStoryNavigationPlugin: require('../../../framework/plugins/GeoStoryNavigation').default,
        GlobeViewSwitcherPlugin: require('../../../framework/plugins/GlobeViewSwitcher'),
        GoFull: require('../../../framework/plugins/GoFull'),
        GridContainerPlugin: require('../../../framework/plugins/GridContainer'),
        GroupManagerPlugin: require('../../../framework/plugins/manager/GroupManager'),
        HelpLinkPlugin: require('../../../framework/plugins/HelpLink').default,
        HelpPlugin: require('../../../framework/plugins/Help'),
        HomePlugin: require('../../../framework/plugins/Home'),
        IdentifyPlugin: require('../../../framework/plugins/Identify'),
        LanguagePlugin: require('../../../framework/plugins/Language'),
        LayerInfoPlugin: require('../../../framework/plugins/LayerInfo').default,
        LocatePlugin: require('../../../framework/plugins/Locate'),
        LoginPlugin: require('../../../framework/plugins/Login'),
        ManagerMenuPlugin: require('../../../framework/plugins/manager/ManagerMenu'),
        ManagerPlugin: require('../../../framework/plugins/manager/Manager'),
        MapEditorPlugin: require('../../../framework/plugins/MapEditor').default,
        MapExportPlugin: require('../../../framework/plugins/MapExport').default,
        MapFooterPlugin: require('../../../framework/plugins/MapFooter'),
        MapImportPlugin: require('../../../framework/plugins/MapImport'),
        MapLoadingPlugin: require('../../../framework/plugins/MapLoading'),
        MapPlugin: require('../../../framework/plugins/Map'),
        MapSearchPlugin: require('../../../framework/plugins/MapSearch'),
        MapsPlugin: require('../../../framework/plugins/Maps'),
        MapCatalogPlugin: require('../../../framework/plugins/MapCatalog').default,
        MapTemplatesPlugin: require('../../../framework/plugins/MapTemplates').default,
        MeasurePlugin: require('../../../framework/plugins/Measure'),
        MediaEditorPlugin: require('../../../framework/plugins/MediaEditor').default,
        MetadataExplorerPlugin: require('../../../framework/plugins/MetadataExplorer'),
        MousePositionPlugin: require('../../../framework/plugins/MousePosition'),
        NotificationsPlugin: require('../../../framework/plugins/Notifications'),
        OmniBarPlugin: require('../../../framework/plugins/OmniBar'),
        PlaybackPlugin: require('../../../framework/plugins/Playback.jsx'),
        PrintPlugin: require('../../../framework/plugins/Print'),
        QueryPanelPlugin: require('../../../framework/plugins/QueryPanel'),
        RedirectPlugin: require('../../../framework/plugins/Redirect'),
        RedoPlugin: require('../../../framework/plugins/History'),
        RulesDataGridPlugin: require('../../../framework/plugins/RulesDataGrid'),
        RulesEditorPlugin: require('../../../framework/plugins/RulesEditor'),
        RulesManagerFooter: require('../../../framework/plugins/RulesManagerFooter'),
        SavePlugin: require('../../../framework/plugins/Save').default,
        SaveAsPlugin: require('../../../framework/plugins/SaveAs').default,
        SaveStoryPlugin: require('../../../framework/plugins/GeoStorySave'),
        ScaleBoxPlugin: require('../../../framework/plugins/ScaleBox'),
        ScrollTopPlugin: require('../../../framework/plugins/ScrollTop'),
        SearchPlugin: require('../../../framework/plugins/Search'),
        SearchServicesConfigPlugin: require('../../../framework/plugins/SearchServicesConfig'),
        SearchByBookmarkPlugin: require('../../../framework/plugins/SearchByBookmark').default,
        SettingsPlugin: require('../../../framework/plugins/Settings'),
        SharePlugin: require('../../../framework/plugins/Share'),
        SnapshotPlugin: require('../../../framework/plugins/Snapshot'),
        StyleEditorPlugin: require('../../../framework/plugins/StyleEditor'),
        TOCItemsSettingsPlugin: require('../../../framework/plugins/TOCItemsSettings').default,
        TOCPlugin: require('../../../framework/plugins/TOC'),
        ThematicLayerPlugin: require('../../../framework/plugins/ThematicLayer'),
        ThemeSwitcherPlugin: require('../../../framework/plugins/ThemeSwitcher'),
        TimelinePlugin: require('../../../framework/plugins/Timeline'),
        ToolbarPlugin: require('../../../framework/plugins/Toolbar'),
        TutorialPlugin: require('../../../framework/plugins/Tutorial'),
        UndoPlugin: require('../../../framework/plugins/History'),
        UserManagerPlugin: require('../../../framework/plugins/manager/UserManager'),
        UserExtensionsPlugin: require('../../../framework/plugins/UserExtensions').default,
        UserSessionPlugin: require('../../../framework/plugins/UserSession').default,
        VersionPlugin: require('../../../framework/plugins/Version'),
        WFSDownloadPlugin: require('../../../framework/plugins/WFSDownload'),
        WidgetsBuilderPlugin: require('../../../framework/plugins/WidgetsBuilder').default,
        WidgetsPlugin: require('../../../framework/plugins/Widgets').default,
        WidgetsTrayPlugin: require('../../../framework/plugins/WidgetsTray').default,
        ZoomAllPlugin: require('../../../framework/plugins/ZoomAll'),
        ZoomInPlugin: require('../../../framework/plugins/ZoomIn'),
        ZoomOutPlugin: require('../../../framework/plugins/ZoomOut')
    },
    requires: {
        ReactSwipe: require('react-swipeable-views').default,
        SwipeHeader: require('../../../framework/components/data/identify/SwipeHeader')
    }
};
